options:
  version:
    type: string
    description: release version of wallabag to install
    default: 1.9.1-b
  server_name:
    type: string
    description: public hostname of server
    default: wallabag
  username:
    type: string
    description: wallabag account username
    default: wallabag
  password:
    type: string
    description: wallabag account password
    default: wallabag
